project:
  type: website
  render:
    - index.qmd
website: 
  title: "Prévisions météo à Montpellier"
  site-path: default
  site-url: https://cmottier.github.io/WeatherRepo/
  repo-url: https://github.com/cmottier/WeatherRepo


format: 
  html: 
    code-fold: false
    theme: cosmo
    backgroundcolor: rgb(178,235,242)
jupyter: python3

